### ISSUE TITLE
BinSearchTree Delete

### ISSUE THREAD

**Issue by HansKiller-TH** [JoJo1541/AlgoDat-Praktikum#1]
@JoJo1541 
Beim Löschen mit nur einem Kind muss geprüft werden, ob das zu löschende Element die Wurzel ist, oder ob der Elternknoten mit der Refernz Left oder Right auf den zu löschenden Knoten zeigt. Und dann entsprechend die passenden Referenzen neu zugewiesen werden.

**Comment by JoJo1541** [comment]
Schaut bitte nochmal drüber, ob das so passt. Wäre nicht das erste mal, dass ich was vergesse...
