### ISSUE TITLE
Treap Delete

### ISSUE THREAD

**Issue by HansKiller-TH** [JoJo1541/AlgoDat-Praktikum#2]
@JoJo1541  Beim tatsächlichen Löschen am Ende der Funktion muss vorher geprüft werden, ob das zu löschende Element die Wurzel ist und das Löschen entsprechend angepasst werden

**Comment by JoJo1541** [comment]
Sollte so passen. Kein Nullpointer mehr, wenn der Baum nur aus Wurzel besteht und selbige gelöäscht wird.
